name: Database CI

on:
 #workflow_dispatch:
  push:
   branches:
    - main
 
 
jobs:

   run-sql-sonar-ci: 
      
       uses: Shanridhu/github-actions-shared-workflow/.github/workflows/databaseci.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
