name: Database CI

on:
 workflow_dispatch:
 # push:
  # branches:
   # - main
 
 
jobs:

   run-sql-sonar-ci: 
      
       uses: lf-common-repo/shared-workflow/.github/workflows/databaseci.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
